version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: test
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: pip
    directory: /machine
    target-branch: test
    schedule:
      interval: weekly
      day: monday
